;(xbindkey '(alt d) "./bin/paste")

;(xbindkey '(alt s) "./bin/runworks")
(xbindkey-function '(shift a)
                   (lambda ()
                    (display "run-command")
                     (run-command "/home/jm/Projects/Apps/hotkey-manager/src/x-sender/test/t3.o 'aaa' 'bbb'"))
)

(xbindkey-function '(shift s)
    (lambda ()
        (display "======111==========")
        (display 'argc)
        (display 'argv)
        (display 'event_type)
        (display 'CODE)
        (display 'BUTTON)
        (display 'SYM)
        (display 'SYM)
        (display "======2222========")
    )
)


(xbindkey-function '(alt a)
    (lambda ()
        (display "======2222========")
    )
)